In [1]:
# Task 1:

In [2]:
# 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

def Divide(x,y):
    try:
        result = x / y
        print("Result: ", result)
    except:
        print("Error: Division by Zero")
    
Divide(5,0)

Error: Division by Zero


In [3]:
# 2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and 
#    verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

#    Hint: Subject,Verb and Object should be declared in the program as shown below.

#    subjects=["Americans ","Indians"]
#    verbs=["play","watch"]
#    objects=["Baseball","Cricket"]

#    Output should come as below:

#    Americans play Baseball.
#    Americans play Cricket.
#    Americans watch Baseball.
#    Americans watch Cricket.
#    Indians play Baseball.
#    Indians play Cricket.
#    Indians watch Baseball.
#    Indians watch Cricket.

subjects = ["Americans", "Indians"]
verbs = ["Play", "Watch"]
objects = ["Baseball","Cricket"]
     
lst = [" ".join([s, v, o]) for s in subjects for v in verbs for o in objects]
for sentence in lst:
    print(sentence)

Americans Play Baseball
Americans Play Cricket
Americans Watch Baseball
Americans Watch Cricket
Indians Play Baseball
Indians Play Cricket
Indians Watch Baseball
Indians Watch Cricket


In [4]:
# Task 2:

In [5]:
# 1. Write a function so that the columns of the output matrix are powers of the input vector.
#    The order of the powers is determined by the increasing boolean argument. Specifically, when
#    increasing is False, the i-th output column is the input vector raised element-wise to the power
#    of N - i - 1.

#    HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
#    Theophile Vandermonde.

import numpy as np

def Vandermonde(vtr, n, increasing):
    rng = range(0,n) if increasing else range(n-1,-1,-1)
    a = np.mat([[i**p for i in vtr] for p in rng])
    return a.T # Transpose of Matrix

vtr = [1, 2, 3, 4, 5]

print("For v =", vtr, "N = 5 increasing = True")
print(Vandermonde(vtr, 5, True))

print(60*"-")

print("For v =", vtr, "N = 5 increasing = False")
print(Vandermonde(vtr, 5, False))

print(60*"-")

print("For v =", vtr, "N = 6 increasing = True")
print(Vandermonde(vtr, 6, True))

print(60*"-")

print("For v =", vtr, "N = 6 increasing = False")
print(Vandermonde(vtr, 6, False))

For v = [1, 2, 3, 4, 5] N = 5 increasing = True
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
------------------------------------------------------------
For v = [1, 2, 3, 4, 5] N = 5 increasing = False
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
------------------------------------------------------------
For v = [1, 2, 3, 4, 5] N = 6 increasing = True
[[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]]
------------------------------------------------------------
For v = [1, 2, 3, 4, 5] N = 6 increasing = False
[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]]
